---
title: "Task2"
author: "Orinta Jautakaitė"
date: '2017 m sausis 20 d '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Tarkime X1 ir X2 yra nepriklausomi, X1∼N(3,2), X2∼N(−1,3) ir X=X1+X2.

```{r}
n=1
x1=rnorm(n, mean = 3, sd = 2)
x2=rnorm(n, mean = -1, sd = 3)
x=x1+x2

```

a)Raskite X teorinį skirstinį. Išbrėžkite tankio grafiką. Pastaba: labai naudinga savybė, kad dviejų natūraliųjų dydžių suma taip pat yra natūralusis dydis.

```{r }
#n=1000
#x1=rnorm(n, mean = 3, sd = 2)
#x2=rnorm(n, mean = -1, sd = 3)
#Stt<-cbind(x1, x2)
#St<-addrv(Stt, sum = x1 + x2)
#S_teor <- marginal(St, vars="sum")
```

b) Sugeneruokite X imtį (N=10000) pagal pateiktą X apibrėžimą.

```{r}
n=10000

x1=rnorm(n, mean = 3, sd = 2)
x2=rnorm(n, mean = -1, sd = 3)

x=x1+x2
```

e) Įvertinkite įvykio $|X| > 2$ tikimybę naudojantis Monte-Carlo metodu.

```{r}
p=sum(x>2) # suskaiciuojame kiek teigiamu reiksmiu yra didesnes uz 2
p2=sum(x<-2) # suskaiciuojame, kiek neigiamu reiksmiu yra mazesnes uz -2
t=(p+p2)/n # sudedame gautus skaicius ir padaliname is elementu skaiciaus
t
```

